aMovieDatabase/core/templates/home.html
The purpose of this pull request is to center-align homepage content.
=> homepage fix

.idea/.gitignore, .idea/a-movie-database.iml, .idea/inspectionProfiles/Project_Default.xml, .idea/inspectionProfiles/profiles_settings.xml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml, aMovieDatabase/accounts/forms.py, aMovieDatabase/accounts/templates/login.html, aMovieDatabase/accounts/templates/register.html, aMovieDatabase/accounts/views.py
Problem was with invalid register form and clearing input fields.On every bad form it was clearing all fields.
=> Register fix

aMovieDatabase/accounts/static/style.css, aMovieDatabase/core/templates/home.html, aMovieDatabase/movies/templates/featured_movies.html, aMovieDatabase/movies/templates/movie_info.html, aMovieDatabase/movies/templates/movies.html, aMovieDatabase/movies/views.py, aMovieDatabase/reviews/templates/author_list.html
=> All together

aMovieDatabase/accounts/static/style.css, aMovieDatabase/movies/templates/movie_info.html, aMovieDatabase/movies/templates/movies.html, aMovieDatabase/movies/views.py
Now you can search by title at filter.
=> Search by title

aMovieDatabase/movies/templates/movies.html, aMovieDatabase/movies/templates/pagination.html, aMovieDatabase/movies/views.py
Fixed slow loading of pagination
=> Pagination AJAX

aMovieDatabase/accounts/static/style.css, aMovieDatabase/movies/templates/movies.html
Some edits for responsive design
=> responsive design edit

aMovieDatabase/accounts/static/style.css, aMovieDatabase/core/templates/home.html, aMovieDatabase/movies/templates/watchlist.html, aMovieDatabase/movies/views.py
Black box at landing page with text now have transparent opacity 60%.
=> Transparent opacity

aMovieDatabase/accounts/static/style.css, aMovieDatabase/movies/templates/watchlist.html, aMovieDatabase/movies/views.py
Now you have your rating / movie rating instead of rating.
=> Label and UI fix

aMovieDatabase/accounts/static/style.css, aMovieDatabase/movies/templates/watchlist.html, aMovieDatabase/movies/views.py
Reverts mehmedkadric/a-movie-database#22
=> Revert "Label and UI fix"

aMovieDatabase/aMovieDatabase/settings.py, aMovieDatabase/aMovieDatabase/urls.py, aMovieDatabase/accounts/static/style.css, aMovieDatabase/core/templates/handle_error.html, aMovieDatabase/core/templates/includes/navbar.html, aMovieDatabase/core/urls.py, aMovieDatabase/core/views.py
=> 404 and 500 error 

aMovieDatabase/movies/models.py
Now user rating is connected with movie model field vote_average.
=> Connect user rating with model

aMovieDatabase/movies/views.py
Now filter affect all top rated movie section.
=> Connect filter and top rated movies

aMovieDatabase/movies/views.py, aMovieDatabase/reviews/templates/author_list.html
Edit a review button with that you can change content of review
=> Edit a review feature

aMovieDatabase/aMovieDatabase/settings.py, aMovieDatabase/accounts/static/style.css
There are some little fix for alignment of text and th/td of table with movies in watchlist tab.
=> Alignment fix for watchlist

aMovieDatabase/movies/filters.py, aMovieDatabase/movies/views.py
Genres are sorted in filter. Also if you apply filter then all movies are sorted by vote_average so you can find  them faster.
=> Sort genres in filter

aMovieDatabase/aMovieDatabase/settings.py, aMovieDatabase/aMovieDatabase/urls.py, aMovieDatabase/movies/views.py, aMovieDatabase/reviews/views.py
Now everything is login_required , so if iser us not logged in and  try to go /movies, he will be redirected to /login
=> Security issue: Movies page is accessible even user is not logged in

aMovieDatabase/accounts/static/style.css, aMovieDatabase/movies/templates/movies.html
Filter is now  more responsive.
=> make movie filter responsive design

aMovieDatabase/accounts/static/style.css, aMovieDatabase/core/templates/includes/navbar.html, aMovieDatabase/movies/filters.py, aMovieDatabase/movies/forms.py, aMovieDatabase/movies/templates/add_movie.html, aMovieDatabase/movies/templates/movie_info.html, aMovieDatabase/movies/templates/movies.html, aMovieDatabase/movies/urls.py, aMovieDatabase/movies/views.py
If you are SUPERUSER then you will get ADD A MOVIE tab where you can add a new movie to DB.
AJAX was missing query params so it was displaying only next page without filter.
Now at movie info you got keywords, and  if you click on them you can find all movies related to selected keyword.
=> Add a movie form, AJAX missing query params fix, Keywords feature at movies detail page

aMovieDatabase/accounts/urls.py, aMovieDatabase/accounts/views.py
Now logout redirect to / instead of /logout
=> Logout button should redirect to homepage

aMovieDatabase/aMovieDatabase/settings.py, aMovieDatabase/accounts/templates/user_info.html, aMovieDatabase/core/templates/contact.html, aMovieDatabase/core/templates/includes/navbar.html, aMovieDatabase/core/urls.py, aMovieDatabase/core/views.py
Contact page added, accessable through the navbar.
=> add a contact page

aMovieDatabase/movies/scoring_algorithm.py, aMovieDatabase/movies/templates/featured_movies.html, aMovieDatabase/movies/templates/pagination.html, aMovieDatabase/movies/views.py
Now top 3 movies are scored by vote average and popularity
=> Enhance movies scoring logic
